# Generated by Django 2.2.5 on 2019-09-16 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('cookie', models.CharField(max_length=200, null=True, verbose_name='cookie')),
            ],
            options={
                'verbose_name': 'Failed authentication',
                'verbose_name_plural': 'Failed authentications',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('login', 'Login'), ('invalid_login', 'Invalid login'), ('invalid_login_mfa', 'Invalid MFA code (login)'), ('password_change', 'Password change'), ('forgot_pass_request', 'Forgot password request'), ('forgot_pass_done', 'Forgot password done'), ('added_MFA', 'Added MFA'), ('removed_MFA', 'Removed MFA'), ('new_codes_MFA', 'New MFA recovery codes'), ('recovery_MFA', 'MFA with recovery code')], max_length=20, verbose_name='type')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('keep', models.BooleanField(default=False, verbose_name='keep')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('location', models.CharField(blank=True, max_length=127, verbose_name='location')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=32, verbose_name='secret_key')),
                ('recovery_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=5)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create')),
            ],
            options={
                'verbose_name': 'User OTP',
                'verbose_name_plural': 'Users OTP',
            },
        ),
    ]
