# Generated by Django 2.1a1 on 2018-06-02 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('login', 'Login'), ('invalid_login', 'Invalid login'), ('password_change', 'Password change'), ('forgot_pass_request', 'Forgot password request'), ('forgot_pass_done', 'Forgot password done'), ('added_MFA', 'Added MFA'), ('added_MFA', 'Removed MFA'), ('recovered_MFA', 'Recovered MFA with codes')], max_length=20, verbose_name='type')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('keep', models.BooleanField(default=False, verbose_name='keep')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('location', models.CharField(blank=True, max_length=127, verbose_name='location')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
