# Generated by Django 2.1a1 on 2018-06-05 19:48

import auth_ex.utils
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0002_auto_20180602_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=127, verbose_name='secret_key')),
                ('recovery_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=auth_ex.utils.generate_mfa_codes, size=5)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User OTP',
                'verbose_name_plural': 'Users OTP',
            },
        ),
    ]
