# Generated by Django 2.2b1 on 2019-03-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0004_auto_20180610_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='secret_key',
            field=models.CharField(max_length=32, verbose_name='secret_key'),
        ),
    ]
