# Generated by Django 2.2.4 on 2019-09-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0005_auto_20190304_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('login', 'Login'), ('invalid_login', 'Invalid login'), ('invalid_login_mfa', 'Invalid MFA code (login)'), ('password_change', 'Password change'), ('forgot_pass_request', 'Forgot password request'), ('forgot_pass_done', 'Forgot password done'), ('added_MFA', 'Added MFA'), ('removed_MFA', 'Removed MFA'), ('new_codes_MFA', 'New MFA recovery codes'), ('recovery_MFA', 'MFA with recovery code')], max_length=20, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='FailedAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('cookie', models.CharField(max_length=200, null=True, verbose_name='cookie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_authentications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Failed authentication',
                'verbose_name_plural': 'Failed authentications',
            },
        ),
        migrations.AddIndex(
            model_name='failedauthentication',
            index=models.Index(fields=['user', 'cookie', '-date'], name='auth_ex_fai_user_id_ea4489_idx'),
        ),
    ]
