version: '3.6'
services:
  postgres:
    image: postgres:alpine
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - static:/static:ro
      - media:/media:ro
    ports:
      - "8000:80"
    depends_on:
      - django
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: dev
      env_file:
        - .env
    depends_on:
      - postgres
    command: uwsgi --ini=./docker/django/uwsgi.ini
    volumes:
      - .:/code
      - static:/static
      - media:/media
volumes:
  pg-data:
    driver: local
  static:
    driver: local
  media:
    driver: local
