version: '3.6'
services:
  redis:
    image: redis:5.0-alpine
  postgres:
    image: postgres:11.5-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
  django:
    image: django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: dev
    env_file:
      - .env
    depends_on:
      - postgres
    command: python src/manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
      - static:/static
      - media:/media
  bootstrap:
    image: django
    command: python src/manage.py bootstrap
    env_file: .env
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 20s
volumes:
  pg-data:
    driver: local
  static:
    driver: local
  media:
    driver: local
