version: '3.6'
services:
  redis:
    image: redis:5.0-alpine
  nginx:
    image: nginx:alpine
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    networks:
      - default
    ports:
      - '1025:80'
    depends_on:
      - django
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        - DJANGO_ENV=prod
    env_file: .env
    networks:
      - default
    secrets:
      - secret_key
      - email_host
      - email_user
      - email_password
      - database_url
      - sentry_url
      - aws_static_id
      - aws_static_secret
      - recaptcha_private_key
  bootstrap:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        - DJANGO_ENV=prod
    command: python src/manage.py bootstrap
    env_file: .env
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 20s
    secrets:
      - secret_key
      - email_host
      - email_user
      - email_password
      - database_url
      - sentry_url
      - aws_static_id
      - aws_static_secret
networks:
  default:
    driver: overlay
secrets:
  secret_key:
    external: true
  email_host:
    external: true
  email_user:
    external: true
  email_password:
    external: true
  database_url:
    external: true
  sentry_url:
    external: true
  aws_static_id:
    external: true
  aws_static_secret:
    external: true
  recaptcha_private_key:
    external: true
