version: '3.6'
services:
  nginx:
    image: 413915321176.dkr.ecr.eu-central-1.amazonaws.com/manager/nginx:${RELEASE}
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    networks:
      - default
    ports:
      - "1025:80"
    depends_on:
      - django
  django:
    image: 413915321176.dkr.ecr.eu-central-1.amazonaws.com/manager/django:${RELEASE}
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        - DJANGO_ENV=prod
    env_file: .env
    networks:
      - default
    command: uwsgi --ini=./docker/django/uwsgi.ini
  bootstrap:
    image: 413915321176.dkr.ecr.eu-central-1.amazonaws.com/manager/django:${RELEASE}
    command: python src/manage.py bootstrap
    env_file: .env
    networks:
      - default
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 20s
networks:
  default:
    driver: overlay
