# Generated by Django 2.1a1 on 2018-06-02 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('password', 'Password'), ('date', 'Date'), ('email', 'Email'), ('url', 'URL'), ('otp', 'One-Time Password')], max_length=24, verbose_name='type')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Safe', max_length=30, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_accessed', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='last accessed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safes', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='SafeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, max_length=5000, verbose_name='notes')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manager.Safe', verbose_name='safe')),
            ],
        ),
        migrations.AddField(
            model_name='itemfield',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='manager.SafeItem', verbose_name='safe item'),
        ),
    ]
