# Generated by Django 2.2b1 on 2019-03-05 23:36

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safe',
            options={'verbose_name': 'Safe', 'verbose_name_plural': 'Safes'},
        ),
        migrations.AlterModelOptions(
            name='safeitem',
            options={'verbose_name': 'Safe item', 'verbose_name_plural': 'Safe items'},
        ),
        migrations.RemoveField(
            model_name='safe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='safe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='safeitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='safe',
            name='data',
            field=models.TextField(blank=True, verbose_name='encrypted data'),
        ),
        migrations.AddField(
            model_name='safe',
            name='image',
            field=models.ImageField(blank=True, upload_to=project.utils.upload_to_classname_uuid, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='safeitem',
            name='data',
            field=models.TextField(blank=True, verbose_name='encrypted data'),
        ),
        migrations.DeleteModel(
            name='ItemField',
        ),
    ]
